export const EPISODES_ACTION_TYPES = {
  // Fetching
  FETCH_ALL_EPISODES: "FETCH_ALL_EPISODES",
  FETCH_ALL_EPISODES_SUCCESS: "FETCH_ALL_EPISODES_SUCCESS",
  FETCH_ALL_EPISODES_FAILURE: "FETCH_ALL_EPISODES_FAILURE",
  // Selection
  SET_SELECTED_EPISODE: "SET_SELECTED_EPISODE",
  CLEAR_SELECTED_EPISODE: "CLEAR_SELECTED_EPISODE",
};

export const CHARACTER_ACTIONS_TYPES = {
  // Fetching
  FETCH_ALL_CHARACTERS: "FETCH_ALL_CHARACTERS",
  FETCH_ALL_CHARACTERS_SUCCESS: "FETCH_ALL_CHARACTERS_SUCCESS",
  FETCH_ALL_CHARACTERS_FAILURE: "FETCH_ALL_CHARACTERS_FAILURE",
  // Selection
  SET_SELECTED_CHARACTER: "SET_SELECTED_CHARACTER",
  CLEAR_SELECTED_CHARACTER: "CLEAR_SELECTED_CHARACTER",
};